.PHONY: run serve schedule queue migrate-up migrate-down test vet build

run: serve

serve:
	go run ./cmd/api serve

schedule:
	go run ./cmd/api schedule

queue:
	go run ./cmd/api queue

migrate-up:
	go run ./cmd/api migrate up

migrate-down:
	go run ./cmd/api migrate down

test:
	go test ./...

vet:
	go vet ./...

build:
	go build -o bin/api ./cmd/api
