.PHONY: run serve schedule queue test build

run: serve

serve:
	go run ./cmd/api serve

schedule:
	go run ./cmd/api schedule

queue:
	go run ./cmd/api queue

test:
	go test ./...

build:
	go build ./cmd/api
